/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-07-22 21:53:01 UTC)
 * on 2014-10-20 at 09:44:05 UTC 
 * Modify at your own risk.
 */

package com.brt.studentapp.model.staffendpoint.model;

/**
 * Model definition for Staff.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the staffendpoint. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Staff extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String jabatan;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Key key;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String name;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String nik;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Text photo;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getJabatan() {
    return jabatan;
  }

  /**
   * @param jabatan jabatan or {@code null} for none
   */
  public Staff setJabatan(java.lang.String jabatan) {
    this.jabatan = jabatan;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Key getKey() {
    return key;
  }

  /**
   * @param key key or {@code null} for none
   */
  public Staff setKey(Key key) {
    this.key = key;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getName() {
    return name;
  }

  /**
   * @param name name or {@code null} for none
   */
  public Staff setName(java.lang.String name) {
    this.name = name;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getNik() {
    return nik;
  }

  /**
   * @param nik nik or {@code null} for none
   */
  public Staff setNik(java.lang.String nik) {
    this.nik = nik;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Text getPhoto() {
    return photo;
  }

  /**
   * @param photo photo or {@code null} for none
   */
  public Staff setPhoto(Text photo) {
    this.photo = photo;
    return this;
  }

  @Override
  public Staff set(String fieldName, Object value) {
    return (Staff) super.set(fieldName, value);
  }

  @Override
  public Staff clone() {
    return (Staff) super.clone();
  }

}
